CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer
(
cId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cName VARCHAR(60),
cAge INT
);
CREATE TABLE Product
(
pId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pName VARCHAR(200) ,
pPrice INT(20)
);
CREATE TABLE `Order`
(
oId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cId INT ,
oDate DATETIME ,
oTotalPrice INT(20),
FOREIGN KEY (cId) REFERENCES Customer (cId)
);
CREATE TABLE OrderDetail
(
oId INT NOT NULL,
pId INT NOT NULL ,
odQTY int ,
FOREIGN KEY (oId) REFERENCES `Order` (oId),
FOREIGN KEY (pId) REFERENCES Product (pId)
);